# Generated by Django 5.1.8 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='offers/', verbose_name='Зображення')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Знижка, %')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Дійсна з')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Дійсна до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Спецпропозиція',
                'verbose_name_plural': 'Спецпропозиції',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
