# Generated by Django 5.2.1 on 2026-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
