# Generated by Django 5.1.8 on 2026-04-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва розділу')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Розділ меню',
                'verbose_name_plural': 'Розділи меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Ресторан м'яса та вина", max_length=150, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('opening_hours', models.CharField(default='13:00 – 23:00', max_length=50, verbose_name='Години роботи')),
                ('breakfast_hours', models.CharField(default='08:00 – 11:00', max_length=50, verbose_name='Сніданки')),
                ('cover_image', models.ImageField(blank=True, upload_to='restaurant/', verbose_name='Обкладинка')),
            ],
            options={
                'verbose_name': 'Інфо про ресторан',
                'verbose_name_plural': 'Інфо про ресторан',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Ціна, грн')),
                ('image', models.ImageField(blank=True, upload_to='restaurant/menu/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.menusection', verbose_name='Розділ')),
            ],
            options={
                'verbose_name': 'Позиція меню',
                'verbose_name_plural': 'Позиції меню',
                'ordering': ['order'],
            },
        ),
    ]
