# Generated by Django 5.2.1 on 2026-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='menusection',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='menusection',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='menusection',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Назва розділу'),
        ),
        migrations.AddField(
            model_name='menusection',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Назва розділу'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_en',
            field=models.CharField(default="Ресторан м'яса та вина", max_length=150, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='title_uk',
            field=models.CharField(default="Ресторан м'яса та вина", max_length=150, null=True, verbose_name='Назва'),
        ),
    ]
