# Generated by Django 5.2.1 on 2026-04-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_description_en_menuitem_description_uk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant/gallery/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Підпис (alt)')),
                ('alt_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис (alt)')),
                ('alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис (alt)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Фото галереї',
                'ordering': ['order'],
            },
        ),
    ]
