# Generated by Django 5.1.8 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours', models.CharField(default='08:00 – 22:00', max_length=50, verbose_name='Години роботи SPA')),
                ('sauna_hours', models.CharField(default='10:00 – 22:00', max_length=50, verbose_name='Години роботи парних')),
                ('description', models.TextField(blank=True, verbose_name='Загальний опис SPA')),
                ('cover_image', models.ImageField(blank=True, upload_to='spa/', verbose_name='Обкладинка SPA')),
            ],
            options={
                'verbose_name': 'Розклад та опис SPA',
                'verbose_name_plural': 'Розклад та опис SPA',
            },
        ),
        migrations.CreateModel(
            name='SpaZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='spa/', verbose_name='Зображення')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Зона SPA',
                'verbose_name_plural': 'Зони SPA',
                'ordering': ['order'],
            },
        ),
    ]
