# Generated by Django 5.2.1 on 2026-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaschedule',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Загальний опис SPA'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Загальний опис SPA'),
        ),
        migrations.AddField(
            model_name='spazone',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='spazone',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='spazone',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='spazone',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Назва'),
        ),
    ]
