# Generated by Django 5.2.1 on 2026-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_spaschedule_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spa/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Підпис')),
                ('caption_uk', models.CharField(blank=True, max_length=120, null=True, verbose_name='Підпис')),
                ('caption_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Підпис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото галереї SPA',
                'verbose_name_plural': 'Галерея SPA',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва пакету')),
                ('title_uk', models.CharField(max_length=120, null=True, verbose_name='Назва пакету')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Назва пакету')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна (грн)')),
                ('duration', models.CharField(max_length=60, verbose_name='Тривалість')),
                ('features', models.TextField(help_text='По одному пункту на рядок', verbose_name='Склад пакету')),
                ('features_uk', models.TextField(help_text='По одному пункту на рядок', null=True, verbose_name='Склад пакету')),
                ('features_en', models.TextField(help_text='По одному пункту на рядок', null=True, verbose_name='Склад пакету')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Найпопулярніший')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Пакет SPA',
                'verbose_name_plural': 'Пакети SPA',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_1_icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Іконка 1 (emoji або SVG id)'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_1_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Підпис 1'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_1_label_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Підпис 1'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_1_label_uk',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Підпис 1'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_2_icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Іконка 2 (emoji або SVG id)'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_2_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Підпис 2'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_2_label_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Підпис 2'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_2_label_uk',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Підпис 2'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_3_icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Іконка 3 (emoji або SVG id)'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_3_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Підпис 3'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_3_label_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Підпис 3'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='highlight_3_label_uk',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Підпис 3'),
        ),
    ]
