# Generated by Django 5.2.1 on 2026-04-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_spagallery_spapackage_spaschedule_highlight_1_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaschedule',
            name='stat_1_label',
            field=models.CharField(default='м² площа SPA', max_length=80, verbose_name='Стат. 1 — підпис'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_1_label_en',
            field=models.CharField(default='м² площа SPA', max_length=80, null=True, verbose_name='Стат. 1 — підпис'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_1_label_uk',
            field=models.CharField(default='м² площа SPA', max_length=80, null=True, verbose_name='Стат. 1 — підпис'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_1_value',
            field=models.CharField(default='600+', max_length=20, verbose_name='Стат. 1 — значення'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_2_label',
            field=models.CharField(default='м панорамний басейн', max_length=80, verbose_name='Стат. 2 — підпис'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_2_label_en',
            field=models.CharField(default='м панорамний басейн', max_length=80, null=True, verbose_name='Стат. 2 — підпис'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_2_label_uk',
            field=models.CharField(default='м панорамний басейн', max_length=80, null=True, verbose_name='Стат. 2 — підпис'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_2_value',
            field=models.CharField(default='20×8', max_length=20, verbose_name='Стат. 2 — значення'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_3_label',
            field=models.CharField(default='wellness-зон', max_length=80, verbose_name='Стат. 3 — підпис'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_3_label_en',
            field=models.CharField(default='wellness-зон', max_length=80, null=True, verbose_name='Стат. 3 — підпис'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_3_label_uk',
            field=models.CharField(default='wellness-зон', max_length=80, null=True, verbose_name='Стат. 3 — підпис'),
        ),
        migrations.AddField(
            model_name='spaschedule',
            name='stat_3_value',
            field=models.CharField(default='6', max_length=20, verbose_name='Стат. 3 — значення'),
        ),
    ]
