# Generated by Django 5.1.8 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('short_description', models.TextField(verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Повний опис')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Іконка (emoji або svg)')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Зображення')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order'],
            },
        ),
    ]
