# Generated by Django 5.1.8 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Підзаголовок')),
                ('image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Зображення')),
                ('cta_text', models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки')),
                ('cta_url', models.CharField(blank=True, default='#booking', max_length=200, verbose_name='URL кнопки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Слайд Hero',
                'verbose_name_plural': 'Слайди Hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Затишний Двір', max_length=100, verbose_name='Назва сайту')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Слоган')),
                ('logo', models.ImageField(blank=True, upload_to='core/', verbose_name='Логотип')),
                ('logo_white', models.ImageField(blank=True, upload_to='core/', verbose_name='Логотип білий')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('phone_secondary', models.CharField(blank=True, max_length=30, verbose_name='Телефон 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('map_embed', models.TextField(blank=True, verbose_name='Embed код Google Maps')),
                ('hero_video', models.FileField(blank=True, upload_to='core/video/', verbose_name='Відео для Hero')),
                ('hero_video_poster', models.ImageField(blank=True, upload_to='core/', verbose_name='Постер для відео')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram URL')),
                ('viber_url', models.URLField(blank=True, verbose_name='Viber URL')),
                ('about_text', models.TextField(blank=True, verbose_name='Текст "Про нас"')),
                ('about_image', models.ImageField(blank=True, upload_to='core/', verbose_name='Фото "Про нас"')),
                ('check_in_time', models.CharField(default='15:00', max_length=10, verbose_name='Час заїзду')),
                ('check_out_time', models.CharField(default='11:00', max_length=10, verbose_name='Час виїзду')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
