# Generated by Django 5.1.8 on 2026-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Наприклад: 22, 5★, 20×8, 2 хв', max_length=20, verbose_name='Значення')),
                ('label', models.CharField(help_text='Наприклад: Номерів та апартаментів', max_length=100, verbose_name='Підпис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Відображати')),
            ],
            options={
                'verbose_name': 'Статистика на головній',
                'verbose_name_plural': 'Статистика на головній',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(default='SPA Resort • Буковель', help_text='Маленький текст над головним заголовком на першому екрані', max_length=100, verbose_name='Підпис над заголовком Hero'),
        ),
    ]
