# Generated by Django 5.2.1 on 2026-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statitem_sitesettings_hero_eyebrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_text_uk',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст "Про нас"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст "Про нас"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_en',
            field=models.CharField(default='SPA Resort • Буковель', help_text='Маленький текст над головним заголовком на першому екрані', max_length=100, null=True, verbose_name='Підпис над заголовком Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_uk',
            field=models.CharField(default='SPA Resort • Буковель', help_text='Маленький текст над головним заголовком на першому екрані', max_length=100, null=True, verbose_name='Підпис над заголовком Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='Затишний Двір', max_length=100, null=True, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_uk',
            field=models.CharField(default='Затишний Двір', max_length=100, null=True, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='statitem',
            name='label_en',
            field=models.CharField(help_text='Наприклад: Номерів та апартаментів', max_length=100, null=True, verbose_name='Підпис'),
        ),
        migrations.AddField(
            model_name='statitem',
            name='label_uk',
            field=models.CharField(help_text='Наприклад: Номерів та апартаментів', max_length=100, null=True, verbose_name='Підпис'),
        ),
    ]
