# Generated by Django 5.2.1 on 2026-05-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_heroslide_cta_text_en_heroslide_cta_text_uk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBootstrap',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Bootstrap-мітка',
                'verbose_name_plural': 'Bootstrap-мітки',
            },
        ),
    ]
