# Generated by Django 5.1.8 on 2026-04-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name="Ім'я та прізвище")),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('check_in', models.DateField(verbose_name='Дата заїзду')),
                ('check_out', models.DateField(verbose_name='Дата виїзду')),
                ('adults', models.PositiveSmallIntegerField(default=2, verbose_name='Дорослих')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Дітей')),
                ('message', models.TextField(blank=True, verbose_name='Побажання')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('contacted', "Зв'язались"), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адреса')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='rooms.roomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Заявка на бронювання',
                'verbose_name_plural': 'Заявки на бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
