# Generated by Django 5.1.8 on 2026-04-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('area_m2', models.PositiveSmallIntegerField(default=30, verbose_name='Площа, м²')),
                ('max_guests', models.PositiveSmallIntegerField(default=2, verbose_name='Макс. гостей')),
                ('beds', models.CharField(blank=True, max_length=100, verbose_name='Ліжка')),
                ('rooms_count', models.PositiveSmallIntegerField(default=1, verbose_name='Кількість кімнат')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Повний опис')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Ціна від, грн/ніч')),
                ('cover_image', models.ImageField(blank=True, upload_to='rooms/', verbose_name='Обкладинка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типи номерів',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='Alt-текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Зображення номера',
                'verbose_name_plural': 'Зображення номера',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Іконка (emoji або назва)')),
                ('title', models.CharField(max_length=100, verbose_name='Назва фічі')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='rooms.roomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Особливість номера',
                'verbose_name_plural': 'Особливості номера',
                'ordering': ['order'],
            },
        ),
    ]
