# Generated by Django 5.2.1 on 2026-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomfeature',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва фічі'),
        ),
        migrations.AddField(
            model_name='roomfeature',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва фічі'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='beds_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ліжка'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='beds_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ліжка'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Повний опис'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Повний опис'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='short_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Назва'),
        ),
    ]
